package com.example.demo.passenger;

import jakarta.persistence.*;

/**
 * Class name: Passenger
 * @since 2024-11-17
 * @author Miguel Santoscoy
 * Represents a passenger entity in the system. A passenger is associated with a user ID, 
 * and includes basic personal details such as first name, last name, and contact number.
 * The class is annotated with JPA annotations to indicate that it is a persistent entity.
 * The `Passenger` class is used to store and retrieve passenger data from the database.
 * 
 * The class includes fields for the passenger's ID, user ID (which links to the user's account), 
 * first name, last name, and contact number.
 * 
 * It provides getter and setter methods for each field, as well as a `toString` method for 
 * easy display of the object's state.
 */
@Entity
@Table
public class Passenger {

    /**
     * The unique identifier for the passenger, auto-generated by the database using a sequence.
     */
    @Id
    @SequenceGenerator(
            name = "passenger_sequence",
            sequenceName = "passenger_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "passenger_sequence"
    )
    private Integer ID;

    /**
     * The ID of the user associated with this passenger (relates to the user's account).
     */
    private Integer UserID;

    /**
     * The first name of the passenger.
     */
    private String fName;

    /**
     * The last name of the passenger.
     */
    private String lName;

    /**
     * The contact number of the passenger.
     */
    private int contactNum;

    /**
     * Constructor to create a new Passenger object with the specified user ID, first name, last name, and contact number.
     * 
     * @param userID     The user ID associated with the passenger.
     * @param fName      The first name of the passenger.
     * @param lName      The last name of the passenger.
     * @param contactNum The contact number of the passenger.
     */
    public Passenger(int userID, String fName, String lName, int contactNum) {
        this.UserID = userID;
        this.fName = fName;
        this.lName = lName;
        this.contactNum = contactNum;
    }

    /**
     * Gets the contact number of the passenger.
     * 
     * @return The contact number of the passenger.
     */
    public int getContactNum() {
        return contactNum;
    }

    /**
     * Gets the last name of the passenger.
     * 
     * @return The last name of the passenger.
     */
    public String getlName() {
        return lName;
    }

    /**
     * Gets the first name of the passenger.
     * 
     * @return The first name of the passenger.
     */
    public String getfName() {
        return fName;
    }

    /**
     * Gets the user ID associated with the passenger.
     * 
     * @return The user ID of the passenger.
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * Gets the unique identifier for the passenger.
     * 
     * @return The ID of the passenger.
     */
    public int getID() {
        return ID;
    }

    /**
     * Sets the unique identifier for the passenger.
     * 
     * @param ID The ID to be set for the passenger.
     */
    public void setID(int ID) {
        this.ID = ID;
    }

    /**
     * Sets the user ID associated with the passenger.
     * 
     * @param userID The user ID to be set for the passenger.
     */
    public void setUserID(int userID) {
        UserID = userID;
    }

    /**
     * Sets the first name of the passenger.
     * 
     * @param fName The first name to be set for the passenger.
     */
    public void setfName(String fName) {
        this.fName = fName;
    }

    /**
     * Sets the last name of the passenger.
     * 
     * @param lName The last name to be set for the passenger.
     */
    public void setlName(String lName) {
        this.lName = lName;
    }

    /**
     * Sets the contact number of the passenger.
     * 
     * @param contactNum The contact number to be set for the passenger.
     */
    public void setContactNum(int contactNum) {
        this.contactNum = contactNum;
    }

    /**
     * Returns a string representation of the passenger, including all the passenger's details.
     * 
     * @return A string representing the passenger object.
     */
    @Override
    public String toString() {
        return "Passenger{" +
                "ID=" + ID +
                ", UserID=" + UserID +
                ", fName='" + fName + '\'' +
                ", lName='" + lName + '\'' +
                ", contactNum=" + contactNum +
                '}';
    }
}
